GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9jZWx5biIsImlhdCI6MTYyMDEyNjI5MiwiZXhwIjoxNjIwMTI2MzIyfQ.oPr6wCfH6wD636ay94n5aW4tTgCuLn6TTt_qVNw0VW4

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9jZWx5biIsImlhdCI6MTYyMDEyNjI5Mn0.LM9Hy8cE4pPxB_Stqgl5r1A0pe3QTRHRYQP2vqShpCw"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9jZWx5biIsImlhdCI6MTYyMDEyNjI5Mn0.LM9Hy8cE4pPxB_Stqgl5r1A0pe3QTRHRYQP2vqShpCw"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jocelyn"
}